default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: citizen_api_development

test:
  <<: *default
  database: citizen_api_test

production:
  <<: *default
  database: citizen_api_production
  username: citizen_api
  password: <%= ENV['CITIZEN_API_DATABASE_PASSWORD'] %>
